name: CI/CD NuGet

on:
  push:
    branches:
      - add-ci
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies core
        run: dotnet restore TaskOrchestrator.sln

      - name: Build core
        run: dotnet build TaskOrchestrator.sln --configuration Release

      - name: Test
        run: dotnet test Tests/Tests.csproj --configuration Release --no-build
